# Generated by Django 3.0.6 on 2020-12-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_fasta',
            field=models.BooleanField(default=True),
        ),
    ]
