# Generated by Django 3.0.6 on 2020-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_upload_is_fasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_paired',
            field=models.BooleanField(default=False),
        ),
    ]
