# Generated by Django 3.0.6 on 2020-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190903_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_uuid',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
    ]
